"""Add deposit receipt fields to DailySettlement

Revision ID: 60a963390ade
Revises: 02ebfba0458e
Create Date: 2026-03-16 08:56:49.819755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a963390ade'
down_revision = '02ebfba0458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_receipt_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('deposit_ocr_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deposit_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_settlement', schema=None) as batch_op:
        batch_op.drop_column('deposit_verified')
        batch_op.drop_column('deposit_ocr_amount')
        batch_op.drop_column('deposit_receipt_path')

    # ### end Alembic commands ###
